# CI script
image: localhost:5000/sayayi-jdk:17

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: ".gradle-cache"

before_script:
  - export JAVA_HOME="/usr/lib/jvm/jdk-17"
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle-cache

build:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew clean build releaseAllDryRun -Psigning.keyId=$SIGNING_KEY_ID -Psigning.password=$SIGNING_PASSWORD -Psigning.secretKeyRingFile=/var/lib/pgp/0F69E7AAD65F2E81-keys.asc
#    - ./gradlew docs -Ddocumentation=true
  artifacts:
    name: "message-format-artifacts"
    paths:
      - message-format/.build/libs/*.jar
      - message-format-annotations/.build/libs/*.jar
      - message-format-asm/.build/libs/*.jar
      - message-format-spring/.build/libs/*.jar
      - message-gradle-plugin/.build/libs/*.jar
    expire_in: 2 weeks
