# CI script
image: localhost:5000/sayayi-jdk:17

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: ".gradle-cache"

before_script:
  - export JAVA_HOME="/usr/lib/jvm/jdk-17"
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle-cache

build:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew clean build -Dtest-pack-compat=true --info
    - ./gradlew docs
  artifacts:
    name: "message-format-artifacts"
    paths:
      - message-format/.build/libs/*.jar
      - message-format-jodatime/.build/libs/*.jar
      - message-gradle-plugin/.build/libs/*.jar
    expire_in: 2 weeks
