# CI script
image: java:8-jdk

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: ".gradle-cache"

before_script:
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle-cache

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - ./message-format/.build/libs/*.jar
      - ./message-format-cpscan/.build/libs/*.jar
      - ./message-format-jodatime/.build/libs/*.jar
      - ./message-format-jsr354/.build/libs/*.jar
    exclude:
      - ./message-format/.build/libs/message-format-test-*.jar
    expire_in: 2 weeks
