# CI script
image: openjdk:17-slim-buster

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: ".gradle-cache"

before_script:
  - export JAVA_HOME="/usr/local/openjdk-17"
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle-cache

build:
  stage: build
  tags:
    - docker
  script: ./gradlew clean build --info --stacktrace
  artifacts:
    name: "message-format-artifacts"
    paths:
      - message-format/.build/libs/*.jar
      - message-format-jodatime/.build/libs/*.jar
    expire_in: 2 weeks
