# CI script
image: java:8-jdk

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: ".gradle-cache"

before_script:
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle-cache

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - ./message-format/.build/libs/*
      - ./message-format-java7/.build/libs/*
      - ./message-format-java8/.build/libs/*
      - ./message-format-jodatime/.build/libs/*
      - ./message-format-jsr354/.build/libs/*
    expire_in: 8 weeks
