# CI script
image: java:17-jdk

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: ".gradle-cache"

before_script:
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle-cache

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    name: "message-format-artifacts"
    paths:
      - message-format/.build/libs/*.jar
      - message-format-jodatime/.build/libs/*.jar
    expire_in: 2 weeks
