= Migrate from Version 0.7.x to 0.8.0
:!revnumber:
:sectanchors:

== Parameter format designator

The _format_ designator in `%{<param>,<format>,<data>}` now is used for matching named
parameter formatters only. In previous versions _format_ could be a formatting option as well but
this mixture lead to problems where the formatting option was the same as a named formatter.

As a result of this the formatting options for various parameter formatters have been changed
and/or added.

== Parameter data map

The parameter data map, which used to be similar to a json object inside a parameter definition, has
been flattened. It improves parameter readability as there are less braces.

.Data map (before 0.8.0)
[source]
----
%{n,choice,{0:'no color',1:'1 color','%{n} colors'}}
----

.Data map (since 0.8.0)
[source]
----
%{n,choice,0:'no color',1:'1 color',:'%{n} colors'}
----

== FormatterContext

A formatter context provides a parameter formatter with all information it requires to format an object
and thus reduces the number of method arguments passed to `ParameterFormatter#format(...)`.

.Formatter method (before 0.8.0)
[source,java]
----
@Override
public @NotNull Text format(@NotNull MessageContext messageContext,
                            Object value, String format,
                            @NotNull Parameters parameters, DataMap map)
{
...
}
----

.Formatter method (since 0.8.0)
[source,java]
----
@Override
public @NotNull Text format(@NotNull FormatterContext formatterContext, Object value)
{
...
}
----

Various helper methods from `AbstractParameterFormatter` have been moved to `FormatterContext`.