= Release Notes
:!revnumber:
:toc: left
:toclevels: 1
:sectanchors:

image:https://img.shields.io/github/v/tag/jgremmen/message-format?label=release[GitHub tag (latest SemVer)]
image:https://img.shields.io/github/languages/code-size/jgremmen/message-format[GitHub code size in bytes]
image:https://img.shields.io/github/last-commit/jgremmen/message-format[GitHub last commit]
image:https://img.shields.io/github/license/jgremmen/message-format[GitHub]

[[release-0.8.0]]
== 0.8.0
_Release date: t.b.d._

====== New

* Add named formatter `clip`
* Introduce `FormatterContext` for `ParameterFormatter#format(...)` method
* A parameter formatter can delegate formatting to the next (based on formattable type priority) formatter

====== Change

* Flatten parameter data map, eg. `%{n,choice,1:'color',:'colors'}`
* Consolidate formatter formatting options

====== Bugfix

* Improve formatter selection based on parameter format designator and value class type
* Parameter format designator is used for selecting a named parameter formatter only

:important-caption:
[IMPORTANT]
This version generally breaks backward compatibility. Please refer to the
xref:migration-guide.adoc#migrate-to-0.8.0[migration guide] for more detailed information.