nav:
  - Home:
    - index.md
    - Philosophy: philosophy.md
    - Version Update:
      - changelog/version-0.23.0.md
      - changelog/version-0.22.0.md
      - changelog/version-0.21.0.md
      - changelog/version-0.20.1.md
      - changelog/version-0.20.0.md
      - changelog/version-0.12.0.md
    - License: license.md
  - Message:
    - message/index.md
    - Syntax: message/syntax.md
    - Formatting: message/formatting.md
  - Config:
    - configuration/index.md
    - Message Support: configuration/message-support.md
    - Message Factory: configuration/message-factory.md
    - Formatter Service: configuration/formatter-service.md
    - Default Configuration: configuration/default-configuration.md
    - Messages and Templates: configuration/messages-and-templates.md
    - Pack Files: configuration/pack-files.md
    - Exceptions: configuration/exceptions.md
  - Formatters:
    - formatter/index.md
    - Parameter Formatters:
      - formatter/parameter/index.md
      - Type-Specific:
        - formatter/parameter/typed/index.md
        - BitSet: formatter/parameter/typed/bit-set.md
        - Boolean: formatter/parameter/typed/boolean.md
        - Byte-Array: formatter/parameter/typed/byte-array.md
        - Charset: formatter/parameter/typed/charset.md
        - Dictionary: formatter/parameter/typed/dictionary.md
        - Enum: formatter/parameter/typed/enum.md
        - Iterable: formatter/parameter/typed/iterable.md
        - Locale: formatter/parameter/typed/locale.md
        - Map: formatter/parameter/typed/map.md
        - Number: formatter/parameter/typed/number.md
        - Optional: formatter/parameter/typed/optional.md
        - Path: formatter/parameter/typed/path.md
        - Reference: formatter/parameter/typed/reference.md
        - String: formatter/parameter/typed/string.md
        - Supplier: formatter/parameter/typed/supplier.md
        - Temporal: formatter/parameter/typed/temporal.md
        - Throwable: formatter/parameter/typed/throwable.md
        - TimeZone: formatter/parameter/typed/time-zone.md
        - Type: formatter/parameter/typed/type.md
        - URI: formatter/parameter/typed/uri.md
        - URL: formatter/parameter/typed/url.md
      - Named:
        - formatter/parameter/named/index.md
        - Bitmask: formatter/parameter/named/bitmask.md
        - Bool: formatter/parameter/named/bool.md
        - Choice: formatter/parameter/named/choice.md
        - Classifier: formatter/parameter/named/classifier.md
        - Geo: formatter/parameter/named/geo.md
        - Size: formatter/parameter/named/size.md
        - SpEL [spring]: formatter/parameter/named/spel.md
        - String: formatter/parameter/named/string.md
    - Post Formatters:
      - formatter/post/index.md
      - Case: formatter/post/case.md
      - Clip: formatter/post/clip.md
    - Development:
      - formatter/development/index.md
      - Parameter:
        - Type-Specific Formatter: formatter/development/typed-parameter-formatter.md
        - Named Formatter: formatter/development/named-parameter-formatter.md
        - Size Queryable: formatter/development/size-queryable.md
        - Map Key Comparator: formatter/development/map-key-comparator.md
      - Post Formatter: formatter/development/post-formatter.md
      - Utilities: formatter/development/utilities.md
  - Adopters:
    - adopter/index.md
    - Annotation: adopter/annotation.md
    - Properties: adopter/properties.md
    - Resource Bundle: adopter/resource-bundle.md
  - Add-Ons:
    - add-on/index.md
    - Log4j: add-on/log4j.md
    - Spring:
      - Message Source: add-on/spring/message-source.md
  - Gradle Plugin:
    - gradle-plugin/index.md
    - Extension Configuration: gradle-plugin/extension.md
    - Pack Task: gradle-plugin/pack-task.md
